package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest) string {
	var b strings.Builder
	b.WriteString("# " + m.Title + "\n\n")
	b.WriteString("<!-- Generated by go run ./tools/providerstatus -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "> Riido task: %s\n\n", m.RiidoTask)
	b.WriteString("Executable SSOT: [`provider-status.riido.json`](provider-status.riido.json).\n\n")
	fmt.Fprintf(&b, "`%s` owns provider status sync/read and store-safe routing guards.\n\n", m.OwnerPackage)
	renderSurfaces(&b, m.Surfaces)
	renderVocabulary(&b, m)
	renderRuleSet(&b, "Sync Validation", m.ValidationRules)
	renderRuleSet(&b, "Store-Safe Routing", m.RoutingRules)
	renderAuth(&b, m.Authorization)
	renderLoop(&b, m.Loop)
	renderSection(&b, "Non-Goals", m.NonGoals)
	return b.String()
}

func renderSurfaces(b *strings.Builder, items []surface) {
	b.WriteString("## Surfaces\n\n| Name | Role |\n| --- | --- |\n")
	for _, item := range items {
		fmt.Fprintf(b, "| `%s` | %s |\n", item.Name, item.Role)
	}
}

func renderVocabulary(b *strings.Builder, m manifest) {
	b.WriteString("\n## Shared Vocabulary\n\n")
	fmt.Fprintf(b, "- routing statuses: %s\n", valueList(m.RoutingStatuses))
	fmt.Fprintf(b, "- distribution channels: %s\n", valueList(m.DistributionChannels))
}

func valueList(items []value) string {
	values := make([]string, 0, len(items))
	for _, item := range items {
		values = append(values, "`"+item.Value+"`")
	}
	return strings.Join(values, ", ")
}
