//go:build ignore

package main

import (
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
)

const exactOwnerSchema = "scalar ControlPlaneFireErrorVoid\n\ntype Query {\n  fireError: ControlPlaneFireErrorVoid\n  healthCheck: Int!\n}\n"

func main() {
	schemaPath := flag.String("schema", "", "owner SDL path")
	outPath := flag.String("out", "", "generated Go output")
	flag.Parse()
	raw, err := os.ReadFile(*schemaPath)
	if err != nil || string(raw) != exactOwnerSchema || *outPath == "" {
		panic("control-plane owner SDL is not the frozen exact schema")
	}
	digest := fmt.Sprintf("%x", sha256.Sum256(raw))
	source := fmt.Sprintf(`// Code generated by control-plane owner registry generator; DO NOT EDIT.

package controlplane

const controlPlaneOwnerSchemaSHA256 = %q

type controlPlaneOwnerOperation struct {
	Name string
	Coordinate string
	CanonicalQuery string
}

func lookupControlPlaneOwnerOperation(name string) (controlPlaneOwnerOperation, bool) {
	switch name {
	case "ControlPlaneOwnerFireError":
		return controlPlaneOwnerOperation{Name: name, Coordinate: "Query.fireError", CanonicalQuery: "queryControlPlaneOwnerFireError{fireError}"}, true
	case "ControlPlaneOwnerHealthCheck":
		return controlPlaneOwnerOperation{Name: name, Coordinate: "Query.healthCheck", CanonicalQuery: "queryControlPlaneOwnerHealthCheck{healthCheck}"}, true
	default:
		return controlPlaneOwnerOperation{}, false
	}
}
`, digest)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		panic(err)
	}
}
