package requirements

const (
	DefaultManifest       = "docs/30-architecture/metrics-http-adapter.riido.json"
	EvidenceSchema        = "riido-metrics-http-adapter-evidence.v1"
	GeneratedNotice       = "<!-- Generated by go run ./tools/metricshttpadapter -write-doc. Do not edit by hand. -->"
	ExpectedID            = "control-plane-metrics-http-adapter"
	ExpectedEndpoint      = "GET /metrics"
	ExpectedMetricsSchema = "riido-ai-server-metrics.v1"
	EvidenceArtifact      = "metrics-http-adapter-evidence"
	Workflow              = ".github/workflows/metrics-http-adapter.yml"
)
