package requirements

const (
	DefaultManifest = "docs/20-domain/saas-control-plane.riido.json"
	ManifestSchema  = "riido-saas-control-plane.v1"
	EvidenceSchema  = "riido-saas-control-plane-evidence.v1"
	ExpectedID      = "saas-control-plane"
	GeneratedNotice = "<!-- Generated by go run ./tools/saascontrolplane -write-doc. Do not edit by hand. -->"
)

var RequiredSharedContracts = []string{
	"github.com/teamswyg/riido-contracts/assignment",
	"github.com/teamswyg/riido-contracts/progressmessage",
	"github.com/teamswyg/riido-contracts/provider/capability",
}
