package main

const (
	defaultManifest = "docs/30-architecture/control-plane-performance.riido.json"
	manifestSchema  = "riido-control-plane-performance.v1"
	evidenceSchema  = "riido-control-plane-performance-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/controlplaneperf -write-doc. Do not edit by hand. -->"
)
