package requirements

const (
	DefaultManifest = "docs/30-architecture/cloudwatch-emf.riido.json"
	EvidenceSchema  = "riido-cloudwatch-emf-evidence.v1"
	GeneratedNotice = "<!-- Generated by go run ./tools/cloudwatchemf -write-doc. Do not edit by hand. -->"
)
