package requirements

const (
	DefaultManifest = "docs/30-architecture/api-client-delivery.riido.json"
	GeneratedNotice = "<!-- Generated by tools/apiclientdelivery; edit api-client-delivery.riido.json instead. -->"
	ManifestSchema  = "riido-control-plane-api-client-delivery.v1"
)
