package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest) string {
	var b strings.Builder
	b.WriteString("# " + m.Title + "\n\n")
	b.WriteString("<!-- Generated by go run ./tools/agentruntimebinding -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "> Riido task: %s\n\n", m.RiidoTask)
	b.WriteString("Executable SSOT: [`agent-runtime-binding.riido.json`](agent-runtime-binding.riido.json).\n\n")
	b.WriteString("## Ownership\n\n")
	fmt.Fprintf(&b, "`%s` owns runtime binding records, assignment provider checks, daemon identity checks, and connected-device binding visibility.\n\n", m.OwnerPackage)
	renderLoop(&b, m.Loop)
	renderFields(&b, m.BindingFields)
	renderRules(&b, "Binding Rules", m.BindingRules)
	renderRules(&b, "Device And Visibility Rules", m.DeviceRules)
	renderSection(&b, "Non-Goals", m.NonGoals)
	return b.String()
}

func renderFields(b *strings.Builder, fields []field) {
	b.WriteString("## Binding Fields\n\n| Field | Required |\n| --- | --- |\n")
	for _, field := range fields {
		fmt.Fprintf(b, "| `%s` | %t |\n", field.Name, field.Required)
	}
}

func renderRules(b *strings.Builder, title string, rules []rule) {
	b.WriteString("\n## " + title + "\n\n| Rule | Kind | Statement |\n| --- | --- | --- |\n")
	for _, rule := range rules {
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", rule.ID, emptyDash(rule.Kind), rule.Rule)
	}
}
