package main

const (
	defaultManifest = "docs/30-architecture/operational-readiness.riido.json"
	manifestSchema  = "riido-control-plane-operational-readiness.v1"
	evidenceSchema  = "riido-control-plane-operational-readiness-evidence.v1"
	candidateSchema = "riido-control-plane-closed-loop-candidates.v1"
	generatedNotice = "<!-- Generated by go run ./tools/operationalreadiness -write-doc. Do not edit by hand. -->"
)

const (
	readinessCandidateSourceID = "operational-readiness"
	readinessCandidateArtifact = "operational-readiness-closed-loop-candidates"
	readinessHarnessLoop       = "operational_readiness_release_harness"
	readinessPromotionTarget   = "closed_loop_candidate"
	readinessNowEnv            = "RIIDO_OPERATIONAL_READINESS_NOW"
)
