package main

const (
	defaultManifest = "docs/30-architecture/operational-readiness.riido.json"
	manifestSchema  = "riido-control-plane-operational-readiness.v1"
	evidenceSchema  = "riido-control-plane-operational-readiness-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/operationalreadiness -write-doc. Do not edit by hand. -->"
)
