package main

const (
	defaultManifest = "docs/30-architecture/go-ci-baseline.riido.json"
	manifestSchema  = "riido-control-plane-go-ci-baseline.v1"
	evidenceSchema  = "riido-control-plane-go-ci-baseline-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/gocibaseline -write-doc. Do not edit by hand. -->"
)
