package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest) string {
	var b strings.Builder
	b.WriteString("# " + m.Title + "\n\n")
	b.WriteString("<!-- Generated by go run ./tools/contextmap -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "> Riido task: %s\n\n", m.RiidoTask)
	b.WriteString("Executable SSOT: [`context-map.riido.json`](context-map.riido.json).\n\n")
	renderOwned(&b, m.OwnedContexts)
	renderImported(&b, m.ImportedContexts)
	renderExternal(&b, m.ExternalContexts)
	renderDirection(&b, m.DirectionRules)
	renderLinks(&b, m.SSOTLinks)
	renderLoop(&b, m.Loop)
	return b.String()
}

func renderOwned(b *strings.Builder, items []ownedContext) {
	b.WriteString("## Owned Contexts\n\n| Context | Public owner | Responsibility |\n| --- | --- | --- |\n")
	for _, item := range items {
		fmt.Fprintf(b, "| %s | `%s` | %s |\n", item.Name, strings.Join(item.OwnerPaths, "`, `"), item.Responsibility)
	}
}

func renderImported(b *strings.Builder, items []importedContext) {
	b.WriteString("\n## Imported Contexts\n\n| Context | Imported from | Use |\n| --- | --- | --- |\n")
	for _, item := range items {
		fmt.Fprintf(b, "| %s | `%s` | %s |\n", item.Name, item.ImportedFrom, item.Use)
	}
}

func renderExternal(b *strings.Builder, items []externalContext) {
	b.WriteString("\n## External Contexts\n\n| Context | Owner | Boundary |\n| --- | --- | --- |\n")
	for _, item := range items {
		fmt.Fprintf(b, "| %s | `%s` | %s |\n", item.Name, item.Owner, item.Boundary)
	}
}
