package main

const (
	defaultManifest = "docs/30-architecture/runtime-deployment-boundary.riido.json"
	generatedNotice = "<!-- Generated by tools/runtimeboundary; edit runtime-deployment-boundary.riido.json instead. -->"
	manifestSchema  = "riido-control-plane-runtime-deployment-boundary.v1"
)
