package main

const (
	defaultManifest = "docs/30-architecture/pre-commit-baseline.riido.json"
	manifestSchema  = "riido-control-plane-pre-commit-baseline.v1"
	evidenceSchema  = "riido-control-plane-pre-commit-baseline-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/precommitbaseline -write-doc. Do not edit by hand. -->"
)
