package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest) string {
	var b strings.Builder
	b.WriteString("# AI Agent Snapshot CQRS Gate\n\n")
	b.WriteString("<!-- Generated by go run ./tools/snapshotcqrsgate -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`ai-agent-snapshot-cqrs-gate.riido.json`](ai-agent-snapshot-cqrs-gate.riido.json).\n\n")
	renderDecision(&b, m)
	renderOperations(&b, m)
	renderMeasurementGate(&b, m)
	renderCandidateSplit(&b, m)
	renderList(&b, "Non-Goals", m.NonGoals)
	renderLoop(&b, m.Loop)
	return b.String()
}

func renderDecision(b *strings.Builder, m manifest) {
	b.WriteString("## Decision\n\n")
	if m.Decision.StoreWideCQRS {
		b.WriteString("Store-wide CQRS is allowed.\n\n")
	} else {
		b.WriteString("Do not promote the whole control-plane Store to CQS/CQRS yet.\n\n")
	}
	fmt.Fprintf(b, "Scope: `%s`.\n\n%s\n\n", m.Decision.Scope, m.Decision.Reason)
}

func renderOperations(b *strings.Builder, m manifest) {
	b.WriteString("## Evidence Shape\n\n")
	for _, item := range m.OperationEvidence {
		fmt.Fprintf(b, "- `%s` (`%s`)\n", item.Route, item.Intent)
		for _, op := range item.StoreOperations {
			fmt.Fprintf(b, "  - `%s`\n", op)
		}
	}
	b.WriteByte('\n')
}
