package main

var coreSurfaceRequired = []string{
	"export type AgentTaskCommentKind",
	"export type RiidoQueryOptions",
	"export type RiidoMutationOptions",
	"aiAgentToken: string",
	"'X-Riido-AI-Agent-Token': config.aiAgentToken",
	"/v2/client/workspaces/${params.workspace_id}/ai-agent/agents",
	"export interface CreateAIAgentV2PathParams",
	"export function createAIAgentV2MutationOptions",
	"계약 generated path: `v2.aiAgent.agents.create`",
	"검색용 generated 경로: `aiAgent.agents.create`",
	"접근 예시: `riido.v2.aiAgent.agents.create`",
	"readonly v2: RiidoV2Module;",
	"/v1/client/ai-agent/tasks/${params.task_id}/assignable-agents",
	"export function listAIAgentTaskThreadsQueryOptions",
	"/v1/client/ai-agent/tasks/${params.task_id}/threads",
	"/v1/client/ai-agent/agents/${params.agent_id}/daemon",
	"export interface AIAgentTaskThreadCollectionResponse",
	"export interface DeviceDaemonRecord",
	"export function getAIAgentDaemonQueryOptions",
	"export function restartAIAgentDaemonMutationOptions",
	"export function submitAIAgentTaskCommentMutationOptions",
	"export function createAIAgentTaskThreadMessageMutationOptions",
	"/v1/client/ai-agent/tasks/${params.task_id}/threads/${params.thread_id}/messages",
	"readonly threadMessages",
	"계약 generated path: `aiAgent.tasks.threadMessages.create`",
	"검색용 generated 경로: `tasks.threadMessages.create`",
	"접근 예시: `riido.aiAgent.tasks.threadMessages.create`",
	"검색용 generated 경로: `onboarding.fixtures.createAgent`",
	"export function stopAIAgentTaskMutationOptions",
	"Promise<AIAgentTaskActionResponse>",
	"export async function streamAIAgentClientEvents",
	"Promise<Response>",
	"이 파일은 tools/reactquerygen으로 생성됩니다. 직접 수정하지 마세요.",
	"AI Agent 설정/온보딩 화면 진입 시 필요한 agent와 device runtime 초기 데이터입니다. agents[]는 settings/list 화면의 agent list이자 agent_id 출처입니다.",
	"web 또는 desktop webview client의 AI Agent 설정/온보딩 초기 데이터와 bootstrap.agents[] agent list를 조회합니다",
	"task 참여자 드롭다운에서는 tasks.assignableAgents.agents[]에서 얻습니다.",
	"cache tag: `aiAgent.tasks.assignableAgents`",
	"export function getAIAgentClientBootstrapQueryOptions",
	"export function listAIAgentTaskAssignableAgentsQueryKeyRoot",
	"export function listAIAgentOnboardingFixturesQueryKeyRoot",
	"export function createAIAgentFromOnboardingFixtureMutationOptions",
	"export interface StopAIAgentTaskMutationVariables",
	"export interface CreateAIAgentFromOnboardingFixtureMutationVariables",
	"export function stopAIAgentTaskMutationOptions",
	"export interface RiidoControlPlaneClient",
	"export interface RiidoAIAgentDevicesNamespace",
	"export interface RiidoAIAgentAgentsDaemonNamespace",
	"export interface RiidoAIAgentOnboardingFixturesNamespace extends ListAIAgentOnboardingFixturesEndpoint",
	"readonly fixtures: RiidoAIAgentOnboardingFixturesNamespace;",
	"readonly daemon",
	"readonly createAgent: CreateAIAgentFromOnboardingFixtureEndpoint;",
	"export function createRiidoControlPlaneClient",
	"readonly queryKeyRoot",
	"readonly invalidateAll",
	"readonly prefetch",
	"invalidates: {",
	"default_visibility: AgentVisibility;",
	"recommended_runtime_kind?: RuntimeKind;",
	"fixture 선택 시 생성 폼에 미리 채울 공개 범위입니다.",
	"fixture에 권장하는 런타임 종류입니다.",
	"import type { QueryClient, UseMutationOptions, UseQueryOptions } from '@/lib/react-query';",
}
