package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest, graph syntaxGraph) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/syntaxhash -write-doc. Do not edit by hand. -->")
	fmt.Fprintf(&b, "\nExecutable SSOT: [`syntax-hash.riido.json`](syntax-hash.riido.json).\n")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Targets")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| Target | Package | Coverage | Syntax Hash | Semantic Claim |")
	fmt.Fprintln(&b, "| --- | --- | ---: | --- | --- |")
	for _, target := range graph.Targets {
		fmt.Fprintf(&b, "| `%s` | `%s` | %d%% | `%s` | `%s` |\n",
			target.ID, target.PackagePath, target.Coverage,
			shortHash(target.PackageHash), target.SemanticClaim)
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Repository Coverage")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- Go files: `%d`\n", graph.Repository.GoFiles)
	fmt.Fprintf(&b, "- tracked files: `%d`\n", graph.Repository.TrackedFiles)
	fmt.Fprintf(&b, "- untracked files: `%d`\n", graph.Repository.UntrackedFiles)
	fmt.Fprintf(&b, "- coverage: `%d.%02d%%`\n",
		graph.Repository.CoverageBasisPoints/100, graph.Repository.CoverageBasisPoints%100)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Constraints")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- max file lines: `%d`\n", graph.Constraints.MaxFileLines)
	fmt.Fprintf(&b, "- max files per folder: `%d`\n", graph.Constraints.MaxFilesPerFolder)
	fmt.Fprintf(&b, "- max directory depth: `%d`\n", graph.Constraints.MaxDepth)
	fmt.Fprintf(&b, "- violations: `%d`\n", graph.Constraints.Violations)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Score")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- formula: `%s`\n", graph.Score.Formula)
	fmt.Fprintf(&b, "- constraint gate: `%s`\n", graph.Score.ConstraintGate)
	fmt.Fprintf(&b, "- tracked files: `%d`\n", graph.Score.TrackedFiles)
	fmt.Fprintf(&b, "- unique syntax hashes: `%d`\n", graph.Score.UniqueSyntaxHashes)
	fmt.Fprintf(&b, "- compression gain: `%d`\n", graph.Score.CompressionGain)
	fmt.Fprintf(&b, "- collision count: `%d`\n", graph.Score.CollisionCount)
	fmt.Fprintf(&b, "- relocation mappings: `%d`\n", graph.Score.RelocationMappings)
	fmt.Fprintf(&b, "- missing relocation mappings: `%d`\n", graph.Score.MissingRelocations)
	fmt.Fprintf(&b, "- relocation coverage: `%d.%02d%%`\n",
		graph.Score.RelocationCoverage/100, graph.Score.RelocationCoverage%100)
	fmt.Fprintf(&b, "- golden commands: `%d`\n", graph.Score.GoldenCommands)
	fmt.Fprintf(&b, "- missing golden commands: `%d`\n", graph.Score.MissingGoldens)
	fmt.Fprintf(&b, "- efficiency score: `%d`\n", graph.Score.EfficiencyScore)
	fmt.Fprintf(&b, "- compression score: `%d`\n", graph.Score.CompressionScore)
	fmt.Fprintf(&b, "- weighted score: `%d`\n", graph.Score.WeightedScore)
	return b.String()
}

func shortHash(value string) string {
	if len(value) < 12 {
		return value
	}
	return value[:12]
}
