package main

const (
	defaultManifest = "docs/30-architecture/review-account-seed.riido.json"
	evidenceSchema  = "riido-review-account-seed-evidence-result.v1"
	generatedNotice = "<!-- Generated by go run ./tools/reviewaccountseed -write-doc. Do not edit by hand. -->"
)
