package main

const (
	defaultManifest = "docs/30-architecture/metrics-http-adapter.riido.json"
	evidenceSchema  = "riido-metrics-http-adapter-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/metricshttpadapter -write-doc. Do not edit by hand. -->"
)
