package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest) string {
	var b strings.Builder
	b.WriteString("# " + m.Title + "\n\n")
	b.WriteString("<!-- Generated by go run ./tools/agentcatalogrbac -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "> Riido task: %s\n\n", m.RiidoTask)
	b.WriteString("Executable SSOT: [`agent-catalog-rbac.riido.json`](agent-catalog-rbac.riido.json).\n\n")
	b.WriteString("## Ownership\n\n")
	fmt.Fprintf(&b, "`%s` owns the public agent catalog RBAC policy, request DTO boundary, and HTTP adapter authorization surface.\n\n", m.OwnerPackage)
	b.WriteString("## Roles And Visibility\n\n")
	renderList(&b, "Roles", m.Roles)
	renderList(&b, "Visibilities", m.Visibilities)
	renderList(&b, "Actions", m.Actions)
	b.WriteString("\n## Visibility And Mutation Rules\n\n")
	b.WriteString("| Rule | Subject | Record | Allowed | Denied | Reason |\n| --- | --- | --- | --- | --- | --- |\n")
	for _, rule := range m.VisibilityRules {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | `%s` |\n", rule.ID, rule.Subject, rule.Record, join(rule.AllowedActions), join(rule.DeniedActions), rule.Reason)
	}
	renderSection(&b, "Authorization Scopes", m.AuthorizationScopes)
	renderSection(&b, "HTTP Routes", m.Routes)
	renderSection(&b, "Request DTOs", m.RequestDTOs)
	renderSection(&b, "Response DTOs", m.ResponseDTOs)
	renderSection(&b, "Store Port Methods", m.StoreMethods)
	renderSection(&b, "Non-Goals", m.NonGoals)
	return b.String()
}

func renderList(b *strings.Builder, label string, values []string) {
	fmt.Fprintf(b, "- %s: %s\n", label, join(values))
}
