package main

const (
	defaultManifest = "docs/30-architecture/store-safe-routing.riido.json"
	evidenceSchema  = "riido-store-safe-routing-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/storesaferouting -write-doc. Do not edit by hand. -->"
)
