package main

const (
	defaultManifest = "docs/migration/control-plane.riido.json"
	manifestSchema  = "riido-control-plane-migration-ledger.v1"
	evidenceSchema  = "riido-control-plane-migration-ledger-evidence.v1"
	expectedID      = "control-plane-migration-ledger"
	expectedTask    = "RIID-4638"
)

const generatedNotice = "<!-- Generated by go run ./tools/migrationledger -write-doc. Do not edit by hand. -->"
