package main

const defaultManifest = "docs/30-architecture/integration-matrix.riido.json"

const evidenceSchema = "riido-control-plane-integration-matrix-evidence.v1"

const generatedNotice = "<!-- Generated by go run ./tools/integrationmatrix -write-doc. Do not edit by hand. -->"
