package main

const (
	defaultManifest = "docs/30-architecture/health-ready-cmd.riido.json"
	evidenceSchema  = "riido-health-ready-cmd-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/healthreadycmd -write-doc. Do not edit by hand. -->"
)
