package main

const defaultManifest = "docs/30-architecture/module-decomposition.riido.json"

const evidenceSchema = "riido-control-plane-module-decomposition-evidence.v1"

const generatedNotice = "<!-- Generated by go run ./tools/moduledecomposition -write-doc. Do not edit by hand. -->"
