package main

const (
	defaultManifest = "docs/30-architecture/ai-agent-generated-endpoint-smoke-matrix.riido.json"
	manifestSchema  = "riido-ai-agent-generated-smoke-matrix-gate.v1"
	evidenceSchema  = "riido-ai-agent-generated-smoke-matrix-evidence.v1"
	expectedID      = "ai-agent-generated-endpoint-smoke-matrix"
)

const generatedNotice = "<!-- Generated by go run ./tools/aigeneratedsmokematrix -write-doc. Do not edit by hand. -->"
