package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest, result verifyResult) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/closedloopcandidateintake -write-doc. Do not edit by hand. -->")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Executable SSOT: [`closed-loop-candidate-intake.riido.json`](closed-loop-candidate-intake.riido.json).")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Summary")
	fmt.Fprintf(&b, "\n- sources: `%d`\n", result.SourceCount)
	fmt.Fprintf(&b, "- required refs: `%d`\n\n", result.RequiredRefs)
	renderSources(&b, m.Sources)
	renderLoop(&b, m.Loop)
	return b.String()
}

func renderSources(b *strings.Builder, sources []intakeSource) {
	fmt.Fprintln(b, "## Sources")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Source | Candidate Artifact | Target | Required Artifacts |")
	fmt.Fprintln(b, "| --- | --- | --- | ---: |")
	for _, source := range sources {
		fmt.Fprintf(b, "| `%s` | `%s` | `%s` | `%d` |\n",
			source.ID, source.CandidateArtifact, source.PromotionTarget, len(source.RequiredNextArtifacts))
	}
	fmt.Fprintln(b)
}
