package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest) string {
	var b strings.Builder
	b.WriteString("# " + m.Title + "\n\n")
	b.WriteString("<!-- Generated by go run ./tools/aiagentclientapi -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "> Riido task: %s\n\n", m.RiidoTask)
	b.WriteString("Executable SSOT: [`ai-agent-client-api.riido.json`](ai-agent-client-api.riido.json).\n\n")
	b.WriteString("Canonical domain changes start in `riido-contracts`; this repo verifies the executable mirror.\n\n")
	renderFiles(&b, m)
	renderCounts(&b, m.OperationCounts)
	renderList(&b, "Required Generated Paths", m.RequiredGeneratedPaths)
	renderList(&b, "Runtime Config Keys", m.RuntimeConfigKeys)
	renderList(&b, "Public Field And Endpoint Signals", m.PublicFields)
	renderList(&b, "Deployment Evidence Phrases", m.DeploymentEvidence)
	renderLoop(&b, m.Loop)
	renderList(&b, "Non-Goals", m.NonGoals)
	return b.String()
}

func renderFiles(b *strings.Builder, m manifest) {
	b.WriteString("## Mirror Files\n\n| Kind | Path |\n| --- | --- |\n")
	rows := [][2]string{{"DSL", m.DSL}, {"IR", m.IR}, {"OpenAPI", m.OpenAPI}, {"Smoke matrix", m.SmokeMatrix}, {"Core client", m.GeneratedCore}, {"React client", m.GeneratedReact}}
	for _, row := range rows {
		fmt.Fprintf(b, "| %s | `%s` |\n", row[0], row[1])
	}
}

func renderCounts(b *strings.Builder, c operationCounts) {
	b.WriteString("\n## Operation Coverage\n\n| Class | Count |\n| --- | ---: |\n")
	fmt.Fprintf(b, "| OpenAPI operations | %d |\n", c.Total)
	fmt.Fprintf(b, "| v1 operations | %d |\n", c.V1)
	fmt.Fprintf(b, "| v2 operations | %d |\n", c.V2)
	fmt.Fprintf(b, "| smoke matrix entries | %d |\n", c.SmokeMatrix)
}
