package main

const (
	manifestSchema  = "riido-control-plane-runtime-cd-ownership.v1"
	evidenceSchema  = "riido-control-plane-runtime-cd-ownership-evidence.v1"
	defaultManifest = "docs/30-architecture/runtime-cd-ownership.riido.json"
	generatedDoc    = "docs/30-architecture/runtime-cd-ownership.md"
	requiredID      = "runtime-cd-ownership"
	requiredTask    = "RIID-4825"
	requiredRuntime = "riido_ai_server"
)

const generatedNotice = "<!-- Generated by go run ./tools/runtimecdownership -write-doc. Do not edit by hand. -->"
