package main

const (
	manifestSchema  = "riido-control-plane-repository-readme.v1"
	evidenceSchema  = "riido-control-plane-repository-readme-evidence.v1"
	defaultManifest = "README.riido.json"
	generatedDoc    = "README.md"
	generatedNotice = "<!-- Generated by go run ./tools/repositoryreadme -write-doc. Do not edit by hand. -->"
)
