package main

const (
	defaultManifest = "docs/30-architecture/cloudwatch-emf.riido.json"
	evidenceSchema  = "riido-cloudwatch-emf-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/cloudwatchemf -write-doc. Do not edit by hand. -->"
)
