package requirements

const (
	DefaultManifest = "docs/30-architecture/ai-agent-generated-endpoint-smoke-matrix.riido.json"
	ManifestSchema  = "riido-ai-agent-generated-smoke-matrix-gate.v1"
	EvidenceSchema  = "riido-ai-agent-generated-smoke-matrix-evidence.v1"
	ExpectedID      = "ai-agent-generated-endpoint-smoke-matrix"
)

const GeneratedNotice = "<!-- Generated by go run ./tools/aigeneratedsmokematrix -write-doc. Do not edit by hand. -->"
