package main

const (
	defaultManifest = "docs/30-architecture/evidence-graph.riido.json"
	manifestSchema  = "riido-control-plane-evidence-graph.v1"
	evidenceSchema  = "riido-control-plane-evidence-graph-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/evidencegraph -write-doc. Do not edit by hand. -->"
)
