package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest, result verifyResult) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/loopregistry -write-doc. Do not edit by hand. -->")
	fmt.Fprintf(&b, "\nExecutable SSOT: [`loop-registry.riido.json`](loop-registry.riido.json).\n\n")
	fmt.Fprintln(&b, "## Summary")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- loops: `%d`\n", result.Loops)
	fmt.Fprintf(&b, "- harness loops: `%d`\n", result.Harnesses)
	fmt.Fprintf(&b, "- closed loops: `%d`\n", result.ClosedLoops)
	fmt.Fprintf(&b, "- claim bindings: `%d`\n", result.Claims)
	fmt.Fprintf(&b, "- evidence graph edges: `%d`\n", result.GraphEdges)
	fmt.Fprintf(&b, "- max evidence expiry hours: `%d`\n\n", result.MaxExpiryHours)
	renderEvidenceKinds(&b, m.EvidenceKinds)
	renderLoops(&b, m.Loops, result)
	renderRefreshPlans(&b, refreshPlans(
		m.Loops,
		m.Claims,
		result.ClaimSurfaces,
		result.RefreshCadenceMinutes,
	))
	renderClaims(&b, m.Claims)
	renderClaimSurfaces(&b, result.ClaimSurfaces)
	renderGraph(&b, m.EvidenceGraph)
	renderLoop(&b, m.Loop)
	return b.String()
}

func renderRefreshPlans(b *strings.Builder, plans []refreshPlan) {
	fmt.Fprintln(b, "## Refresh Plans")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Loop | Workflow | Cadence | Expires | Command | Claims | Verifiers | Next | Evidence |")
	fmt.Fprintln(b, "| --- | --- | ---: | ---: | --- | ---: | ---: | ---: | ---: |")
	for _, plan := range plans {
		fmt.Fprintf(b, "| `%s` | `%s` | `%d` | `%d` | `%s` | `%d` | `%d` | `%d` | `%d` |\n",
			plan.LoopID, plan.WorkflowFile, plan.CadenceMinutes,
			plan.ExpiresAfterHours, plan.ManualRefreshCommand,
			len(plan.ClaimIDs), len(plan.VerifierCommands),
			len(plan.NextCommands), len(plan.EvidenceArtifacts))
	}
	fmt.Fprintln(b)
}

func renderLoops(b *strings.Builder, loops []loopRecord, result verifyResult) {
	fmt.Fprintln(b, "## Loops")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Loop | Kind | Providers | Expires | Refresh Minutes | Refresh Workflow | Promotion Evidence | Evidence |")
	fmt.Fprintln(b, "| --- | --- | --- | ---: | ---: | --- | --- | ---: |")
	for _, loop := range loops {
		promotion := result.HarnessCandidateArtifacts[loop.ID]
		fmt.Fprintf(b, "| `%s` | `%s` | `%s` | `%d` | `%d` | `%s` | `%s` | `%d` |\n",
			loop.ID, loop.Kind, strings.Join(loop.Providers, ", "), loop.ExpiresAfterHours,
			result.RefreshCadenceMinutes[loop.ID], loop.RefreshWorkflow, promotion, len(loop.Evidence))
	}
	fmt.Fprintln(b)
}
