package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest, result verifyResult) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/loopregistry -write-doc. Do not edit by hand. -->")
	fmt.Fprintf(&b, "\nExecutable SSOT: [`loop-registry.riido.json`](loop-registry.riido.json).\n\n")
	fmt.Fprintln(&b, "## Summary")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- loops: `%d`\n", result.Loops)
	fmt.Fprintf(&b, "- harness loops: `%d`\n", result.Harnesses)
	fmt.Fprintf(&b, "- closed loops: `%d`\n", result.ClosedLoops)
	fmt.Fprintf(&b, "- claim bindings: `%d`\n", result.Claims)
	fmt.Fprintf(&b, "- evidence graph edges: `%d`\n", result.GraphEdges)
	fmt.Fprintf(&b, "- max evidence expiry hours: `%d`\n\n", result.MaxExpiryHours)
	renderLoops(&b, m.Loops, result)
	renderClaims(&b, m.Claims)
	renderGraph(&b, m.EvidenceGraph)
	renderLoop(&b, m.Loop)
	return b.String()
}

func renderLoops(b *strings.Builder, loops []loopRecord, result verifyResult) {
	fmt.Fprintln(b, "## Loops")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Loop | Kind | Expires | Refresh Minutes | Refresh Workflow | Promotion Evidence | Evidence |")
	fmt.Fprintln(b, "| --- | --- | ---: | ---: | --- | --- | ---: |")
	for _, loop := range loops {
		promotion := result.HarnessCandidateArtifacts[loop.ID]
		fmt.Fprintf(b, "| `%s` | `%s` | `%d` | `%d` | `%s` | `%s` | `%d` |\n",
			loop.ID, loop.Kind, loop.ExpiresAfterHours,
			result.RefreshCadenceMinutes[loop.ID], loop.RefreshWorkflow, promotion, len(loop.Evidence))
	}
	fmt.Fprintln(b)
}
