// Code generated by tools/riidogen from assignment_contract.riido.json; DO NOT EDIT.

package riidoaiserver

const SchemaVersion = "riido-ai-server.v1"

type AssignmentState string

const (
	AssignmentQueued     AssignmentState = "queued"
	AssignmentLeased     AssignmentState = "leased"
	AssignmentReady      AssignmentState = "ready"
	AssignmentRunning    AssignmentState = "running"
	AssignmentCancelling AssignmentState = "cancelling"
	AssignmentCancelled  AssignmentState = "cancelled"
	AssignmentCompleted  AssignmentState = "completed"
	AssignmentFailed     AssignmentState = "failed"
)

type PollAction string

const (
	PollNone   PollAction = "none"
	PollStart  PollAction = "start"
	PollCancel PollAction = "cancel"
	PollActive PollAction = "active"
)

const (
	EventAssignmentQueued       = "assignment_queued"
	EventAssignmentLeased       = "assignment_leased"
	EventAssignmentReady        = "assignment_ready"
	EventAssignmentRunning      = "assignment_running"
	EventAssignmentCancelling   = "assignment_cancelling"
	EventAssignmentCancelled    = "assignment_cancelled"
	EventAssignmentCompleted    = "assignment_completed"
	EventAssignmentFailed       = "assignment_failed"
	EventAssignmentStateUpdated = "assignment_state_updated"
	EventRiidoLog               = "riido_log"
	EventProviderLog            = "provider_log"
	EventProviderWarning        = "provider_warning"
	EventProviderError          = "provider_error"
)

func isAgentActive(state AssignmentState) bool {
	switch state {
	case AssignmentLeased, AssignmentReady, AssignmentRunning:
		return true
	default:
		return false
	}
}

func isTerminal(state AssignmentState) bool {
	switch state {
	case AssignmentCancelled, AssignmentCompleted, AssignmentFailed:
		return true
	default:
		return false
	}
}

func canTransitionAssignment(from, to AssignmentState) bool {
	if from == to {
		return true
	}
	if isTerminal(from) {
		return false
	}
	switch from {
	case AssignmentQueued:
		switch to {
		case AssignmentLeased, AssignmentCancelling, AssignmentCancelled, AssignmentFailed:
			return true
		default:
			return false
		}
	case AssignmentLeased:
		switch to {
		case AssignmentReady, AssignmentRunning, AssignmentCancelling, AssignmentCancelled, AssignmentFailed:
			return true
		default:
			return false
		}
	case AssignmentReady:
		switch to {
		case AssignmentRunning, AssignmentCancelling, AssignmentCancelled, AssignmentFailed:
			return true
		default:
			return false
		}
	case AssignmentRunning:
		switch to {
		case AssignmentCompleted, AssignmentFailed, AssignmentCancelling, AssignmentCancelled:
			return true
		default:
			return false
		}
	case AssignmentCancelling:
		switch to {
		case AssignmentCancelled, AssignmentFailed:
			return true
		default:
			return false
		}
	default:
		return false
	}
}
