package riidoaiserver

type cloudWatchEMFEnvelope struct {
	AWS                                               cloudWatchEMFMetadata   `json:"_aws"`
	SchemaVersion                                     string                  `json:"schema_version"`
	Service                                           string                  `json:"service"`
	MetricScopeSchemaVersion                          string                  `json:"metric_scope_schema_version"`
	StoreStateMetricScope                             string                  `json:"store_state_metric_scope"`
	HTTPMetricScope                                   string                  `json:"http_metric_scope"`
	StoreOperationMetricScope                         string                  `json:"store_operation_metric_scope"`
	SnapshotPersistenceMetricScope                    string                  `json:"snapshot_persistence_metric_scope"`
	TasksTotal                                        int                     `json:"tasks_total"`
	AssignmentsTotal                                  int                     `json:"assignments_total"`
	AssignmentsQueued                                 int                     `json:"assignments_queued"`
	AssignmentsLeased                                 int                     `json:"assignments_leased"`
	AssignmentsReady                                  int                     `json:"assignments_ready"`
	AssignmentsRunning                                int                     `json:"assignments_running"`
	AssignmentsCancelling                             int                     `json:"assignments_cancelling"`
	AssignmentsCancelled                              int                     `json:"assignments_cancelled"`
	AssignmentsCompleted                              int                     `json:"assignments_completed"`
	AssignmentsFailed                                 int                     `json:"assignments_failed"`
	PollRequestsTotal                                 int64                   `json:"poll_requests_total"`
	PollNoneTotal                                     int64                   `json:"poll_none_total"`
	PollStartTotal                                    int64                   `json:"poll_start_total"`
	PollCancelTotal                                   int64                   `json:"poll_cancel_total"`
	PollActiveTotal                                   int64                   `json:"poll_active_total"`
	AgentEventsTotal                                  int64                   `json:"agent_events_total"`
	TaskEventsTotal                                   int64                   `json:"task_events_total"`
	SSESubscribers                                    int                     `json:"sse_subscribers"`
	OutboxErrorsTotal                                 int64                   `json:"outbox_errors_total"`
	EventAppendLatencySamplesTotal                    int64                   `json:"event_append_latency_samples_total"`
	EventAppendLatencyTotalMilliseconds               int64                   `json:"event_append_latency_total_ms"`
	EventAppendLatencyMaxMilliseconds                 int64                   `json:"event_append_latency_max_ms"`
	EventAppendLatencyLastMilliseconds                int64                   `json:"event_append_latency_last_ms"`
	HTTPRequestsTotal                                 int64                   `json:"http_requests_total"`
	HTTPResponse2xxTotal                              int64                   `json:"http_response_2xx_total"`
	HTTPResponse3xxTotal                              int64                   `json:"http_response_3xx_total"`
	HTTPResponse4xxTotal                              int64                   `json:"http_response_4xx_total"`
	HTTPResponse5xxTotal                              int64                   `json:"http_response_5xx_total"`
	HTTPRequestLatencySamplesTotal                    int64                   `json:"http_request_latency_samples_total"`
	HTTPRequestLatencyTotalMilliseconds               int64                   `json:"http_request_latency_total_ms"`
	HTTPRequestLatencyMaxMilliseconds                 int64                   `json:"http_request_latency_max_ms"`
	HTTPRequestLatencyLastMilliseconds                int64                   `json:"http_request_latency_last_ms"`
	HTTPTransactions                                  []HTTPTransactionMetric `json:"http_transactions,omitempty"`
	StoreOperationCallsTotal                          int64                   `json:"store_operation_calls_total"`
	StoreOperationErrorsTotal                         int64                   `json:"store_operation_errors_total"`
	StoreOperationLatencySamplesTotal                 int64                   `json:"store_operation_latency_samples_total"`
	StoreOperationLatencyTotalMilliseconds            int64                   `json:"store_operation_latency_total_ms"`
	StoreOperationLatencyMaxMilliseconds              int64                   `json:"store_operation_latency_max_ms"`
	StoreOperationLatencyLastMilliseconds             int64                   `json:"store_operation_latency_last_ms"`
	StoreOperations                                   []StoreOperationMetric  `json:"store_operations,omitempty"`
	AIAgentClientSnapshotLoadCallsTotal               int64                   `json:"ai_agent_client_snapshot_load_calls_total"`
	AIAgentClientSnapshotLoadErrorsTotal              int64                   `json:"ai_agent_client_snapshot_load_errors_total"`
	AIAgentClientSnapshotLoadBytesTotal               int64                   `json:"ai_agent_client_snapshot_load_bytes_total"`
	AIAgentClientSnapshotLoadBytesMax                 int64                   `json:"ai_agent_client_snapshot_load_bytes_max"`
	AIAgentClientSnapshotLoadBytesLast                int64                   `json:"ai_agent_client_snapshot_load_bytes_last"`
	AIAgentClientSnapshotLoadLatencySamplesTotal      int64                   `json:"ai_agent_client_snapshot_load_latency_samples_total"`
	AIAgentClientSnapshotLoadLatencyTotalMilliseconds int64                   `json:"ai_agent_client_snapshot_load_latency_total_ms"`
	AIAgentClientSnapshotLoadLatencyMaxMilliseconds   int64                   `json:"ai_agent_client_snapshot_load_latency_max_ms"`
	AIAgentClientSnapshotLoadLatencyLastMilliseconds  int64                   `json:"ai_agent_client_snapshot_load_latency_last_ms"`
	AIAgentClientSnapshotSaveCallsTotal               int64                   `json:"ai_agent_client_snapshot_save_calls_total"`
	AIAgentClientSnapshotSaveErrorsTotal              int64                   `json:"ai_agent_client_snapshot_save_errors_total"`
	AIAgentClientSnapshotSaveBytesTotal               int64                   `json:"ai_agent_client_snapshot_save_bytes_total"`
	AIAgentClientSnapshotSaveBytesMax                 int64                   `json:"ai_agent_client_snapshot_save_bytes_max"`
	AIAgentClientSnapshotSaveBytesLast                int64                   `json:"ai_agent_client_snapshot_save_bytes_last"`
	AIAgentClientSnapshotSaveLatencySamplesTotal      int64                   `json:"ai_agent_client_snapshot_save_latency_samples_total"`
	AIAgentClientSnapshotSaveLatencyTotalMilliseconds int64                   `json:"ai_agent_client_snapshot_save_latency_total_ms"`
	AIAgentClientSnapshotSaveLatencyMaxMilliseconds   int64                   `json:"ai_agent_client_snapshot_save_latency_max_ms"`
	AIAgentClientSnapshotSaveLatencyLastMilliseconds  int64                   `json:"ai_agent_client_snapshot_save_latency_last_ms"`
}
