package riidoaiserver

func cloudWatchMetricSpecs() []cloudWatchMetricSpec {
	specs := []cloudWatchMetricSpec{
		{Name: "tasks_total", Unit: "Count"},
		{Name: "assignments_total", Unit: "Count"},
		{Name: "assignments_queued", Unit: "Count"},
		{Name: "assignments_leased", Unit: "Count"},
		{Name: "assignments_ready", Unit: "Count"},
		{Name: "assignments_running", Unit: "Count"},
		{Name: "assignments_cancelling", Unit: "Count"},
		{Name: "assignments_cancelled", Unit: "Count"},
		{Name: "assignments_completed", Unit: "Count"},
		{Name: "assignments_failed", Unit: "Count"},
		{Name: "poll_requests_total", Unit: "Count"},
		{Name: "poll_none_total", Unit: "Count"},
		{Name: "poll_start_total", Unit: "Count"},
		{Name: "poll_cancel_total", Unit: "Count"},
		{Name: "poll_active_total", Unit: "Count"},
		{Name: "agent_events_total", Unit: "Count"},
		{Name: "task_events_total", Unit: "Count"},
		{Name: "sse_subscribers", Unit: "Count"},
		{Name: "outbox_errors_total", Unit: "Count"},
		{Name: "event_append_latency_samples_total", Unit: "Count"},
		{Name: "event_append_latency_total_ms", Unit: "Milliseconds"},
		{Name: "event_append_latency_max_ms", Unit: "Milliseconds"},
		{Name: "event_append_latency_last_ms", Unit: "Milliseconds"},
		{Name: "http_requests_total", Unit: "Count"},
		{Name: "http_response_2xx_total", Unit: "Count"},
		{Name: "http_response_3xx_total", Unit: "Count"},
		{Name: "http_response_4xx_total", Unit: "Count"},
		{Name: "http_response_5xx_total", Unit: "Count"},
		{Name: "http_request_latency_samples_total", Unit: "Count"},
		{Name: "http_request_latency_total_ms", Unit: "Milliseconds"},
		{Name: "http_request_latency_max_ms", Unit: "Milliseconds"},
		{Name: "http_request_latency_last_ms", Unit: "Milliseconds"},
		{Name: "store_operation_calls_total", Unit: "Count"},
		{Name: "store_operation_errors_total", Unit: "Count"},
		{Name: "store_operation_latency_samples_total", Unit: "Count"},
		{Name: "store_operation_latency_total_ms", Unit: "Milliseconds"},
		{Name: "store_operation_latency_max_ms", Unit: "Milliseconds"},
		{Name: "store_operation_latency_last_ms", Unit: "Milliseconds"},
		{Name: "ai_agent_client_snapshot_load_calls_total", Unit: "Count"},
		{Name: "ai_agent_client_snapshot_load_errors_total", Unit: "Count"},
		{Name: "ai_agent_client_snapshot_load_bytes_total", Unit: "Bytes"},
		{Name: "ai_agent_client_snapshot_load_bytes_max", Unit: "Bytes"},
		{Name: "ai_agent_client_snapshot_load_bytes_last", Unit: "Bytes"},
		{Name: "ai_agent_client_snapshot_load_latency_samples_total", Unit: "Count"},
		{Name: "ai_agent_client_snapshot_load_latency_total_ms", Unit: "Milliseconds"},
		{Name: "ai_agent_client_snapshot_load_latency_max_ms", Unit: "Milliseconds"},
		{Name: "ai_agent_client_snapshot_load_latency_last_ms", Unit: "Milliseconds"},
		{Name: "ai_agent_client_snapshot_save_calls_total", Unit: "Count"},
		{Name: "ai_agent_client_snapshot_save_errors_total", Unit: "Count"},
		{Name: "ai_agent_client_snapshot_save_bytes_total", Unit: "Bytes"},
		{Name: "ai_agent_client_snapshot_save_bytes_max", Unit: "Bytes"},
		{Name: "ai_agent_client_snapshot_save_bytes_last", Unit: "Bytes"},
		{Name: "ai_agent_client_snapshot_save_latency_samples_total", Unit: "Count"},
		{Name: "ai_agent_client_snapshot_save_latency_total_ms", Unit: "Milliseconds"},
		{Name: "ai_agent_client_snapshot_save_latency_max_ms", Unit: "Milliseconds"},
		{Name: "ai_agent_client_snapshot_save_latency_last_ms", Unit: "Milliseconds"},
	}
	return append([]cloudWatchMetricSpec(nil), specs...)
}
