package riidoaiserver

func applyCloudWatchEMFSnapshotPersistence(envelope *cloudWatchEMFEnvelope, snapshot MetricsSnapshot) {
	envelope.AIAgentClientSnapshotLoadCallsTotal = snapshot.AIAgentClientSnapshotLoadCallsTotal
	envelope.AIAgentClientSnapshotLoadErrorsTotal = snapshot.AIAgentClientSnapshotLoadErrorsTotal
	envelope.AIAgentClientSnapshotLoadBytesTotal = snapshot.AIAgentClientSnapshotLoadBytesTotal
	envelope.AIAgentClientSnapshotLoadBytesMax = snapshot.AIAgentClientSnapshotLoadBytesMax
	envelope.AIAgentClientSnapshotLoadBytesLast = snapshot.AIAgentClientSnapshotLoadBytesLast
	envelope.AIAgentClientSnapshotLoadLatencySamplesTotal = snapshot.AIAgentClientSnapshotLoadLatencySamplesTotal
	envelope.AIAgentClientSnapshotLoadLatencyTotalMilliseconds = snapshot.AIAgentClientSnapshotLoadLatencyTotalMilliseconds
	envelope.AIAgentClientSnapshotLoadLatencyMaxMilliseconds = snapshot.AIAgentClientSnapshotLoadLatencyMaxMilliseconds
	envelope.AIAgentClientSnapshotLoadLatencyLastMilliseconds = snapshot.AIAgentClientSnapshotLoadLatencyLastMilliseconds
	envelope.AIAgentClientSnapshotSaveCallsTotal = snapshot.AIAgentClientSnapshotSaveCallsTotal
	envelope.AIAgentClientSnapshotSaveErrorsTotal = snapshot.AIAgentClientSnapshotSaveErrorsTotal
	envelope.AIAgentClientSnapshotSaveBytesTotal = snapshot.AIAgentClientSnapshotSaveBytesTotal
	envelope.AIAgentClientSnapshotSaveBytesMax = snapshot.AIAgentClientSnapshotSaveBytesMax
	envelope.AIAgentClientSnapshotSaveBytesLast = snapshot.AIAgentClientSnapshotSaveBytesLast
	envelope.AIAgentClientSnapshotSaveLatencySamplesTotal = snapshot.AIAgentClientSnapshotSaveLatencySamplesTotal
	envelope.AIAgentClientSnapshotSaveLatencyTotalMilliseconds = snapshot.AIAgentClientSnapshotSaveLatencyTotalMilliseconds
	envelope.AIAgentClientSnapshotSaveLatencyMaxMilliseconds = snapshot.AIAgentClientSnapshotSaveLatencyMaxMilliseconds
	envelope.AIAgentClientSnapshotSaveLatencyLastMilliseconds = snapshot.AIAgentClientSnapshotSaveLatencyLastMilliseconds
}
