// Code generated by control-plane owner registry generator; DO NOT EDIT.

package riidoaiserver

const controlPlaneOwnerSchemaSHA256 = "ce69c0c3c4556b7dcb6db92522a1e53e386c3c631bb1c88b821774e2364779b7"

type controlPlaneOwnerOperation struct {
	Name           string
	Coordinate     string
	CanonicalQuery string
}

func lookupControlPlaneOwnerOperation(name string) (controlPlaneOwnerOperation, bool) {
	switch name {
	case "ControlPlaneOwnerFireError":
		return controlPlaneOwnerOperation{Name: name, Coordinate: "Query.fireError", CanonicalQuery: "queryControlPlaneOwnerFireError{fireError}"}, true
	case "ControlPlaneOwnerHealthCheck":
		return controlPlaneOwnerOperation{Name: name, Coordinate: "Query.healthCheck", CanonicalQuery: "queryControlPlaneOwnerHealthCheck{healthCheck}"}, true
	default:
		return controlPlaneOwnerOperation{}, false
	}
}
