package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest, result verifyResult) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/closedloopcandidatedecision -write-doc. Do not edit by hand. -->")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Executable SSOT: [`closed-loop-candidate-decision.riido.json`](closed-loop-candidate-decision.riido.json).")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Summary")
	fmt.Fprintf(&b, "\n- decisions: `%d`\n", result.DecisionCount)
	fmt.Fprintf(&b, "- command artifact: `%s`\n\n", m.CommandArtifact)
	renderAssertions(&b, m.Assertions)
	renderDecisions(&b, m.Decisions)
	renderDecisionTemplates(&b, m.DecisionTemplates)
	renderLoop(&b, m.Loop)
	return b.String()
}

func renderAssertions(b *strings.Builder, assertions []string) {
	fmt.Fprintln(b, "## Assertions")
	fmt.Fprintln(b)
	for _, assertion := range assertions {
		fmt.Fprintf(b, "- %s\n", assertion)
	}
	fmt.Fprintln(b)
}

func renderDecisions(b *strings.Builder, decisions []decisionRecord) {
	fmt.Fprintln(b, "## Decisions")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Candidate | Disposition | Priority | Owner | Review By | Next Artifact |")
	fmt.Fprintln(b, "| --- | --- | --- | --- | --- | --- |")
	for _, decision := range decisions {
		fmt.Fprintf(b, "| `%s` | `%s` | `%s` | `%s` | `%s` | `%s` |\n",
			decision.CandidateID, decision.Disposition, decision.Priority,
			decision.Owner, decision.ReviewBy, decision.NextArtifact)
	}
	fmt.Fprintln(b)
}
