package requirements

const (
	DefaultManifest = "docs/30-architecture/review-account-seed.riido.json"
	EvidenceSchema  = "riido-review-account-seed-evidence-result.v1"
	GeneratedNotice = "<!-- Generated by go run ./tools/reviewaccountseed -write-doc. Do not edit by hand. -->"
)
