package main

const (
	defaultManifest = "docs/30-architecture/loop-closure-audit.riido.json"
	manifestSchema  = "riido-control-plane-loop-closure-audit.v1"
	evidenceSchema  = "riido-control-plane-loop-closure-audit-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/loopclosureaudit -write-doc. Do not edit by hand. -->"
)
