package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest, result verifyResult) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/harnesspromotion -write-doc. Do not edit by hand. -->")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Executable SSOT: [`harness-promotion.riido.json`](harness-promotion.riido.json).")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Summary")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- promotion sources: `%d`\n", result.SourceCount)
	fmt.Fprintf(&b, "- required next artifact refs: `%d`\n\n", result.ClaimCount)
	fmt.Fprintf(&b, "- loop registry: `%s`\n\n", m.LoopRegistryManifest)
	renderSources(&b, m.Sources)
	renderAssertions(&b, m.Assertions)
	renderLoop(&b, m.Loop)
	return b.String()
}

func renderSources(b *strings.Builder, sources []promotionSource) {
	fmt.Fprintln(b, "## Promotion Sources")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Source | Harness Loop | Candidate Artifact | Target | Required Next Artifacts |")
	fmt.Fprintln(b, "| --- | --- | --- | --- | ---: |")
	for _, source := range sources {
		fmt.Fprintf(b, "| `%s` | `%s` | `%s` | `%s` | `%d` |\n",
			source.ID, source.HarnessLoop, source.CandidateArtifact,
			source.PromotionTarget, len(source.RequiredNextArtifacts))
	}
	fmt.Fprintln(b)
}

func renderAssertions(b *strings.Builder, assertions []string) {
	fmt.Fprintln(b, "## Assertions")
	fmt.Fprintln(b)
	for _, assertion := range assertions {
		fmt.Fprintf(b, "- %s\n", assertion)
	}
	fmt.Fprintln(b)
}
