package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest, result verifyResult) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/harnesspromotion -write-doc. Do not edit by hand. -->")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Executable SSOT: [`harness-promotion.riido.json`](harness-promotion.riido.json).")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Summary")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- promotion sources: `%d`\n", result.SourceCount)
	fmt.Fprintf(&b, "- required next artifact refs: `%d`\n\n", result.ClaimCount)
	renderSources(&b, m.Sources)
	renderLoop(&b, m.Loop)
	return b.String()
}

func renderSources(b *strings.Builder, sources []promotionSource) {
	fmt.Fprintln(b, "## Promotion Sources")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Source | Harness Loop | Candidate Artifact | Target |")
	fmt.Fprintln(b, "| --- | --- | --- | --- |")
	for _, source := range sources {
		fmt.Fprintf(b, "| `%s` | `%s` | `%s` | `%s` |\n",
			source.ID, source.HarnessLoop, source.CandidateArtifact, source.PromotionTarget)
	}
	fmt.Fprintln(b)
}
