package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest) string {
	var b strings.Builder
	b.WriteString("# " + m.Title + "\n\n")
	b.WriteString("<!-- Generated by go run ./tools/requestauth -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "> Riido task: %s\n\n", m.RiidoTask)
	b.WriteString("Executable SSOT: [`request-authorization.riido.json`](request-authorization.riido.json).\n\n")
	fmt.Fprintf(&b, "`%s` owns request-token, device-principal, and external authorizer semantics.\n\n", m.OwnerPackage)
	renderSurfaces(&b, m.Surfaces)
	renderList(&b, "Resources", m.Resources)
	renderTransports(&b, m.TokenTransports)
	renderList(&b, "Runtime Config Keys", m.RuntimeConfigKeys)
	renderList(&b, "External Contract Versions", m.ExternalContractVersions)
	renderRuleGroups(&b, m.RuleGroups)
	renderLoop(&b, m.Loop)
	renderList(&b, "Non-Goals", m.NonGoals)
	return b.String()
}

func renderSurfaces(b *strings.Builder, items []surface) {
	b.WriteString("## Surfaces\n\n| Name | Role |\n| --- | --- |\n")
	for _, item := range items {
		fmt.Fprintf(b, "| `%s` | %s |\n", item.Name, item.Role)
	}
}

func renderTransports(b *strings.Builder, items []transport) {
	b.WriteString("\n## Token Transports\n\n")
	for _, item := range items {
		fmt.Fprintf(b, "- `%s`: `%s`\n", item.ID, item.Value)
	}
}

func renderList(b *strings.Builder, title string, items []string) {
	b.WriteString("\n## " + title + "\n\n")
	fmt.Fprintf(b, "- %s\n", codeList(items))
}

func codeList(items []string) string {
	values := make([]string, 0, len(items))
	for _, item := range items {
		values = append(values, "`"+item+"`")
	}
	return strings.Join(values, ", ")
}
