package main

const (
	defaultManifest = "docs/50-roadmap/open-questions.riido.json"
	generatedNotice = "<!-- Generated by tools/openquestions; edit open-questions.riido.json instead. -->"
	manifestSchema  = "riido-control-plane-open-questions.v1"
)
