package main

const (
	defaultManifest = "docs/30-architecture/control-plane-high-traffic-audit.riido.json"
	manifestSchema  = "riido-control-plane-high-traffic-audit.v1"
	evidenceSchema  = "riido-control-plane-high-traffic-audit-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/controlplaneaudit -write-doc. Do not edit by hand. -->"
)
