package main

import (
	"strings"
	"testing"
)

func TestContractArtifactRequiresOwnerEvidence(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "contracts/api.json", "{}")
	mustWrite(t, root, "docs/api.md", "<!-- Generated by tools/apicheck. -->\n")
	mustWrite(t, root, "docs/api.riido.json", contractOwnerFixture("contracts/api.json"))
	mustWrite(t, root, ".github/workflows/api.yml", contractWorkflowFixture("warn"))
	artifact := contractArtifact{
		Path: "contracts/api.json", OwnerManifest: "docs/api.riido.json", OwnerKey: "openapi",
	}
	problems := validateContractArtifact(root, artifact)
	if len(problems) == 0 || !strings.Contains(problems[0], "strict generated evidence") {
		t.Fatalf("problems = %#v", problems)
	}
	mustWrite(t, root, ".github/workflows/api.yml", contractWorkflowFixture("error"))
	if problems := validateContractArtifact(root, artifact); len(problems) != 0 {
		t.Fatalf("strict contract artifact failed: %#v", problems)
	}
}

func TestContractArtifactRequiresOwnerDeclaration(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/api.riido.json", contractOwnerFixture("contracts/other.json"))
	artifact := contractArtifact{
		Path: "contracts/api.json", OwnerManifest: "docs/api.riido.json", OwnerKey: "openapi",
	}
	problems := validateContractArtifact(root, artifact)
	if len(problems) == 0 || !strings.Contains(problems[0], "must declare artifact path") {
		t.Fatalf("problems = %#v", problems)
	}
}

func contractOwnerFixture(path string) string {
	return `{"generated_doc":"docs/api.md","workflow":".github/workflows/api.yml",` +
		`"evidence_artifact":"api-evidence","openapi":"` + path + `"}`
}

func contractWorkflowFixture(mode string) string {
	return "" +
		"steps:\n" +
		"  - run: go run ./tools/apicheck -check-doc -evidence-out out/api.json\n" +
		"  - uses: actions/upload-artifact@v4\n" +
		"    with:\n" +
		"      name: api-evidence\n" +
		"      path: out/api.json\n" +
		"      if-no-files-found: " + mode + "\n"
}
