package main

type evidence struct {
	SchemaVersion                    string         `json:"schema_version"`
	ID                               string         `json:"id"`
	Status                           string         `json:"status"`
	ScannedCount                     int            `json:"scanned_count"`
	GeneratedCount                   int            `json:"generated_count"`
	GeneratedToolCount               int            `json:"generated_tool_count"`
	GeneratedEvidenceWorkflowCount   int            `json:"generated_evidence_workflow_count"`
	GeneratedDeclaredWorkflowCount   int            `json:"generated_declared_workflow_evidence_count"`
	GeneratedManifestEvidenceTool    int            `json:"generated_manifest_evidence_tool_count"`
	GeneratedArtifactBindingCount    int            `json:"generated_artifact_binding_count"`
	DirectSSOTCount                  int            `json:"direct_ssot_count"`
	StandaloneManifestCount          int            `json:"standalone_manifest_count"`
	StandaloneManifestBindingCount   int            `json:"standalone_manifest_binding_count"`
	SourceManifestCount              int            `json:"source_manifest_count"`
	SourceManifestBindingCount       int            `json:"source_manifest_binding_count"`
	ContractArtifactCount            int            `json:"contract_artifact_count"`
	ContractArtifactBindingCount     int            `json:"contract_artifact_binding_count"`
	ImportedManifestCount            int            `json:"imported_manifest_count"`
	ImportedManifestBindingCount     int            `json:"imported_manifest_binding_count"`
	OwnedManifestCount               int            `json:"owned_manifest_count"`
	OwnedManifestBindingCount        int            `json:"owned_manifest_binding_count"`
	ManifestInventoryCount           int            `json:"manifest_inventory_count"`
	TrackedManifestCount             int            `json:"tracked_manifest_count"`
	ManualCount                      int            `json:"manual_count"`
	ManualByGroup                    map[string]int `json:"manual_by_group"`
	ManualTopDirs                    []manualDir    `json:"manual_top_dirs"`
	ManualSamples                    []manualSample `json:"manual_samples"`
	GeneratedMissingTool             []string       `json:"generated_missing_tool"`
	GeneratedMissingWorkflow         []string       `json:"generated_missing_workflow"`
	GeneratedMissingEvidenceWorkflow []string       `json:"generated_missing_evidence_workflow"`
	GeneratedMissingDeclaredWorkflow []string       `json:"generated_missing_declared_workflow_evidence"`
	GeneratedEvidenceToolMismatch    []string       `json:"generated_manifest_evidence_tool_mismatch"`
	GeneratedMissingArtifactBinding  []string       `json:"generated_missing_artifact_binding"`
	DirectLoopCount                  int            `json:"direct_ssot_loop_count"`
	DirectEvidenceWorkflowCount      int            `json:"direct_ssot_evidence_workflow_count"`
	StandaloneMissingBinding         []string       `json:"standalone_manifest_missing_binding"`
	SourceMissingBinding             []string       `json:"source_manifest_missing_binding"`
	ContractMissingBinding           []string       `json:"contract_artifact_missing_binding"`
	ImportedMissingBinding           []string       `json:"imported_manifest_missing_binding"`
	OwnedMissingBinding              []string       `json:"owned_manifest_missing_binding"`
	UntrackedManifests               []string       `json:"untracked_manifests"`
	DirectMissingEvidenceWorkflow    []string       `json:"direct_ssot_missing_evidence_workflow"`
	DirectMissingLoop                []string       `json:"direct_ssot_missing_loop"`
	ProblemSummaries                 []string       `json:"problem_summaries"`
	EvidenceArtifact                 string         `json:"evidence_artifact"`
	Loop                             evidenceLoop   `json:"loop"`
}
