package main

import (
	"strings"
	"testing"
)

func TestScanRejectsGeneratedDocWhenArtifactMissesEvidenceOutPath(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/generated.md", "<!-- Generated by go run ./tools/example -write-doc. -->\n")
	mustWrite(t, root, "docs/generated.riido.json", `{"generated_doc":"docs/generated.md","workflow":".github/workflows/example.yml","evidence_artifact":"example-evidence"}`)
	mustWrite(t, root, "tools/example/main.go", "package main\n")
	mustWrite(t, root, ".github/workflows/example.yml", mismatchedEvidenceOutWorkflow())
	m := manifest{ScanRoots: []string{"docs"}}
	_, problems := scanDocs(root, m)
	if len(problems) == 0 || !strings.Contains(strings.Join(problems, "\n"), "evidence-out path") {
		t.Fatalf("problems = %#v", problems)
	}
}

func TestScanRejectsGeneratedDocWhenStrictStepMissesEvidenceOutPath(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/generated.md", "<!-- Generated by go run ./tools/example -write-doc. -->\n")
	mustWrite(t, root, "docs/generated.riido.json", `{"generated_doc":"docs/generated.md","workflow":".github/workflows/example.yml","evidence_artifact":"example-evidence"}`)
	mustWrite(t, root, "tools/example/main.go", "package main\n")
	mustWrite(t, root, ".github/workflows/example.yml", splitStrictEvidenceOutWorkflow())
	m := manifest{ScanRoots: []string{"docs"}}
	_, problems := scanDocs(root, m)
	if len(problems) == 0 || !strings.Contains(strings.Join(problems, "\n"), "strict artifact step") {
		t.Fatalf("problems = %#v", problems)
	}
}

func mismatchedEvidenceOutWorkflow() string {
	return "steps:\n" +
		"  - run: go run ./tools/example -check-doc -evidence-out out/example.json\n" +
		"  - uses: actions/upload-artifact@v7\n" +
		"    with:\n" +
		"      name: example-evidence\n" +
		"      path: out/other.json\n" +
		"      if-no-files-found: error\n"
}

func splitStrictEvidenceOutWorkflow() string {
	return "steps:\n" +
		"  - run: go run ./tools/example -check-doc -evidence-out out/example.json\n" +
		"  - uses: actions/upload-artifact@v7\n" +
		"    with:\n" +
		"      name: example-evidence\n" +
		"      path: out/example.json\n" +
		"  - uses: actions/upload-artifact@v7\n" +
		"    with:\n" +
		"      name: example-evidence\n" +
		"      path: out/other.json\n" +
		"      if-no-files-found: error\n"
}
