package main

import (
	"strings"
	"testing"
)

func TestScanRejectsGeneratedDocWithoutWorkflowReference(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/generated.md", "<!-- Generated by go run ./tools/example -write-doc. -->\n")
	mustWrite(t, root, "tools/example/main.go", "package main\n")
	m := manifest{ScanRoots: []string{"docs"}}
	_, problems := scanDocs(root, m)
	if len(problems) == 0 || !strings.Contains(problems[0], "not referenced by CI workflow") {
		t.Fatalf("problems = %#v", problems)
	}
}

func TestScanRejectsGeneratedDocWithoutWorkflowEvidence(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/generated.md", "<!-- Generated by go run ./tools/example -write-doc. -->\n")
	mustWrite(t, root, "docs/generated.riido.json", `{"generated_doc":"docs/generated.md","workflow":".github/workflows/example.yml","evidence_artifact":"example-evidence"}`)
	mustWrite(t, root, "tools/example/main.go", "package main\n")
	mustWrite(t, root, ".github/workflows/example.yml", "steps:\n  - run: go test ./tools/example\n")
	m := manifest{ScanRoots: []string{"docs"}}
	_, problems := scanDocs(root, m)
	if len(problems) == 0 || !strings.Contains(strings.Join(problems, "\n"), "must run check-doc with evidence-out") {
		t.Fatalf("problems = %#v", problems)
	}
}

func TestScanRejectsGeneratedDocWithoutUploadedArtifact(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/generated.md", "<!-- Generated by go run ./tools/example -write-doc. -->\n")
	mustWrite(t, root, "docs/generated.riido.json", `{"generated_doc":"docs/generated.md","workflow":".github/workflows/example.yml","evidence_artifact":"example-evidence"}`)
	mustWrite(t, root, "tools/example/main.go", "package main\n")
	mustWrite(t, root, ".github/workflows/example.yml", "steps:\n  - run: go run ./tools/example -check-doc -evidence-out out/example.json\n")
	m := manifest{ScanRoots: []string{"docs"}}
	_, problems := scanDocs(root, m)
	if len(problems) == 0 || !strings.Contains(strings.Join(problems, "\n"), "must upload evidence artifact") {
		t.Fatalf("problems = %#v", problems)
	}
}

func TestScanRejectsGeneratedDocWhenDeclaredWorkflowDoesNotRunTool(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/generated.md", "<!-- Generated by go run ./tools/example -write-doc. -->\n")
	mustWrite(t, root, "docs/generated.riido.json", `{"generated_doc":"docs/generated.md","workflow":".github/workflows/other.yml","evidence_artifact":"example-evidence"}`)
	mustWrite(t, root, "tools/example/main.go", "package main\n")
	mustWrite(t, root, ".github/workflows/example.yml", "steps:\n  - run: go run ./tools/example -check-doc -evidence-out out/example.json\n")
	mustWrite(t, root, ".github/workflows/other.yml", "steps:\n- uses: actions/upload-artifact@v4\n  with:\n    name: example-evidence\n    if-no-files-found: error\n")
	m := manifest{ScanRoots: []string{"docs"}}
	_, problems := scanDocs(root, m)
	if len(problems) == 0 || !strings.Contains(strings.Join(problems, "\n"), "must run generator") {
		t.Fatalf("problems = %#v", problems)
	}
}
