package main

import (
	"strings"
	"testing"
)

func TestScanRejectsGeneratedManifestEvidenceToolMismatch(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/generated.md", "<!-- Generated by go run ./tools/example -write-doc. -->\n")
	mustWrite(t, root, "docs/generated.riido.json", evidenceToolMismatchManifest())
	mustWrite(t, root, "tools/example/main.go", "package main\n")
	mustWrite(t, root, ".github/workflows/example.yml", completeExampleEvidenceWorkflow())
	m := manifest{ScanRoots: []string{"docs"}}
	_, problems := scanDocs(root, m)
	if len(problems) == 0 || !strings.Contains(strings.Join(problems, "\n"), "evidence_tool") {
		t.Fatalf("problems = %#v", problems)
	}
}

func evidenceToolMismatchManifest() string {
	return `{"generated_doc":"docs/generated.md","workflow":".github/workflows/example.yml",` +
		`"evidence_artifact":"example-evidence","evidence_tool":"tools/other"}`
}

func completeExampleEvidenceWorkflow() string {
	return "steps:\n" +
		"  - run: go run ./tools/example -check-doc -evidence-out out/example.json\n" +
		"  - uses: actions/upload-artifact@v7\n" +
		"    with:\n" +
		"      name: example-evidence\n" +
		"      path: out/example.json\n" +
		"      if-no-files-found: error\n"
}
