package main

import "testing"

func TestGeneratedToolFromMarker(t *testing.T) {
	cases := map[string]string{
		"<!-- Generated by go run ./tools/moduledecomposition -write-doc. Do not edit by hand. -->": "tools/moduledecomposition",
		"<!-- Generated by tools/openquestions; edit open-questions.riido.json instead. -->":        "tools/openquestions",
	}
	for marker, want := range cases {
		if got := generatedToolFromMarker(marker); got != want {
			t.Fatalf("generatedToolFromMarker(%q) = %q, want %q", marker, got, want)
		}
	}
}
