package main

import (
	"strings"
	"testing"
)

func TestScanRejectsGeneratedDocWithoutWorkflowReference(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/generated.md", "<!-- Generated by go run ./tools/example -write-doc. -->\n")
	mustWrite(t, root, "tools/example/main.go", "package main\n")
	m := manifest{ScanRoots: []string{"docs"}}
	_, problems := scanDocs(root, m)
	if len(problems) == 0 || !strings.Contains(problems[0], "not referenced by CI workflow") {
		t.Fatalf("problems = %#v", problems)
	}
}
