package main

import (
	"strings"
	"testing"
)

func TestImportedManifestRequiresProjectionEvidence(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "contracts/source.riido.json", importedSourceFixture("source.v1", "source-id"))
	mustWrite(t, root, "docs/projection.md", "<!-- Generated by tools/projection. -->\n")
	mustWrite(t, root, "docs/projection.riido.json", importedOwnerFixture("source.v1", "source-id"))
	mustWrite(t, root, ".github/workflows/projection.yml", importedWorkflowFixture("warn"))
	imported := importedManifestFixture()
	problems := validateImportedManifest(root, imported)
	if len(problems) == 0 || !strings.Contains(problems[0], "strict generated evidence") {
		t.Fatalf("problems = %#v", problems)
	}
	mustWrite(t, root, ".github/workflows/projection.yml", importedWorkflowFixture("error"))
	if problems := validateImportedManifest(root, imported); len(problems) != 0 {
		t.Fatalf("strict imported manifest failed: %#v", problems)
	}
}

func TestImportedManifestRequiresMatchingPointer(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "contracts/source.riido.json", importedSourceFixture("source.v1", "source-id"))
	mustWrite(t, root, "docs/projection.riido.json", importedOwnerFixture("other.v1", "source-id"))
	problems := validateImportedManifest(root, importedManifestFixture())
	if len(problems) == 0 || !strings.Contains(problems[0], "owner pointer") {
		t.Fatalf("problems = %#v", problems)
	}
}

func importedManifestFixture() importedManifest {
	return importedManifest{
		Path:          "contracts/source.riido.json",
		OwnerManifest: "docs/projection.riido.json",
		OwnerKey:      "source_contracts_manifest",
		UpstreamRepo:  "upstream/contracts",
		UpstreamPath:  "docs/source.riido.json",
		SchemaVersion: "source.v1",
		ID:            "source-id",
	}
}
