package main

import (
	"strings"
	"testing"
)

func TestOwnedManifestRequiresOwnerEvidence(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "internal/seed.riido.json", "{}")
	mustWrite(t, root, "docs/seed.md", "<!-- Generated by tools/seedcheck. -->\n")
	mustWrite(t, root, "docs/seed.riido.json", ownedOwnerFixture("internal/seed.riido.json"))
	mustWrite(t, root, ".github/workflows/seed.yml", ownedWorkflowFixture("warn"))
	owned := ownedManifest{Path: "internal/seed.riido.json", OwnerManifest: "docs/seed.riido.json", OwnerKey: "seed_ssot"}
	problems := validateOwnedManifest(root, owned)
	if len(problems) == 0 || !strings.Contains(problems[0], "strict generated evidence") {
		t.Fatalf("problems = %#v", problems)
	}
	mustWrite(t, root, ".github/workflows/seed.yml", ownedWorkflowFixture("error"))
	if problems := validateOwnedManifest(root, owned); len(problems) != 0 {
		t.Fatalf("strict owned manifest failed: %#v", problems)
	}
}

func TestOwnedManifestRequiresOwnerDeclaration(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/seed.riido.json", ownedOwnerFixture("internal/other.riido.json"))
	owned := ownedManifest{Path: "internal/seed.riido.json", OwnerManifest: "docs/seed.riido.json", OwnerKey: "seed_ssot"}
	problems := validateOwnedManifest(root, owned)
	if len(problems) == 0 || !strings.Contains(problems[0], "must declare owned path") {
		t.Fatalf("problems = %#v", problems)
	}
}

func TestOwnedManifestAcceptsOwnerPathArray(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/readme/overview.riido.json", "{}")
	mustWrite(t, root, "README.md", "<!-- Generated by tools/repositoryreadme. -->\n")
	mustWrite(t, root, "README.riido.json", readmeOwnerFixture())
	mustWrite(t, root, ".github/workflows/readme.yml", readmeWorkflowFixture())
	owned := ownedManifest{
		Path: "docs/readme/overview.riido.json", OwnerManifest: "README.riido.json", OwnerKey: "fragments",
	}
	if problems := validateOwnedManifest(root, owned); len(problems) != 0 {
		t.Fatalf("array-backed owned manifest failed: %#v", problems)
	}
}

func readmeOwnerFixture() string {
	return `{"generated_doc":"README.md","workflow":".github/workflows/readme.yml",` +
		`"evidence_artifact":"repository-readme-evidence",` +
		`"fragments":["docs/readme/overview.riido.json"]}`
}

func readmeWorkflowFixture() string {
	return "" +
		"steps:\n" +
		"  - run: go run ./tools/repositoryreadme -check-doc -evidence-out out/readme.json\n" +
		"  - uses: actions/upload-artifact@v7\n" +
		"    with:\n" +
		"      name: repository-readme-evidence\n" +
		"      path: out/readme.json\n" +
		"      if-no-files-found: error\n"
}
