package main

import (
	"strings"
	"testing"
)

func TestOwnedManifestRequiresOwnerEvidence(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "internal/seed.riido.json", "{}")
	mustWrite(t, root, "docs/seed.md", "<!-- Generated by tools/seedcheck. -->\n")
	mustWrite(t, root, "docs/seed.riido.json", ownedOwnerFixture("internal/seed.riido.json"))
	mustWrite(t, root, ".github/workflows/seed.yml", ownedWorkflowFixture("warn"))
	owned := ownedManifest{Path: "internal/seed.riido.json", OwnerManifest: "docs/seed.riido.json", OwnerKey: "seed_ssot"}
	problems := validateOwnedManifest(root, owned)
	if len(problems) == 0 || !strings.Contains(problems[0], "strict generated evidence") {
		t.Fatalf("problems = %#v", problems)
	}
	mustWrite(t, root, ".github/workflows/seed.yml", ownedWorkflowFixture("error"))
	if problems := validateOwnedManifest(root, owned); len(problems) != 0 {
		t.Fatalf("strict owned manifest failed: %#v", problems)
	}
}

func TestOwnedManifestRequiresOwnerDeclaration(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, "docs/seed.riido.json", ownedOwnerFixture("internal/other.riido.json"))
	owned := ownedManifest{Path: "internal/seed.riido.json", OwnerManifest: "docs/seed.riido.json", OwnerKey: "seed_ssot"}
	problems := validateOwnedManifest(root, owned)
	if len(problems) == 0 || !strings.Contains(problems[0], "must declare owned path") {
		t.Fatalf("problems = %#v", problems)
	}
}
