package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest, docs []docClass, problems []string) string {
	e := buildEvidence(m, docs, problems)
	var b strings.Builder
	b.WriteString("# " + m.Title + "\n\n")
	b.WriteString("<!-- Generated by go run ./tools/knowledgecoverage -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`executable-knowledge.riido.json`](executable-knowledge.riido.json).\n\n")
	b.WriteString("## Coverage\n\n| Class | Count |\n| --- | ---: |\n")
	fmt.Fprintf(&b, "| Generated reader docs | %d |\n", e.GeneratedCount)
	fmt.Fprintf(&b, "| Direct SSOT docs | %d |\n", e.DirectSSOTCount)
	fmt.Fprintf(&b, "| Direct SSOT docs with evidence loop | %d |\n", e.DirectLoopCount)
	fmt.Fprintf(&b, "| Registered manual docs | %d |\n", e.ManualCount)
	fmt.Fprintf(&b, "| Scanned docs | %d |\n\n", e.ScannedCount)
	renderLoop(&b, m.Loop)
	renderManualGroups(&b, m, e)
	renderManualHotspots(&b, e)
	renderManualSamples(&b, e)
	b.WriteString("\n## Assertions\n\n")
	for _, assertion := range m.Assertions {
		b.WriteString("- " + assertion + "\n")
	}
	return b.String()
}

func renderLoop(b *strings.Builder, loop evidenceLoop) {
	b.WriteString("## Evidence Loop\n\n| Step | Statement |\n| --- | --- |\n")
	fmt.Fprintf(b, "| Observe | %s |\n", loop.Observation)
	fmt.Fprintf(b, "| Hypothesis | %s |\n", loop.Hypothesis)
	fmt.Fprintf(b, "| Execute | %s |\n", loop.Execute)
	fmt.Fprintf(b, "| Evaluate | %s |\n", loop.Evaluate)
	fmt.Fprintf(b, "| Retrospective | %s |\n\n", loop.Retrospective)
}

func renderManualGroups(b *strings.Builder, m manifest, e evidence) {
	b.WriteString("## Registered Manual Surfaces\n\n")
	if len(m.ManualGroups) == 0 {
		b.WriteString("None.\n")
		return
	}
	b.WriteString("| Group | Owner | Next artifact | Matched docs |\n| --- | --- | --- | ---: |\n")
	for _, group := range m.ManualGroups {
		fmt.Fprintf(b, "| `%s` | %s | %s | %d |\n", group.ID, group.Owner, group.NextArtifact, e.ManualByGroup[group.ID])
	}
}

func renderManualHotspots(b *strings.Builder, e evidence) {
	b.WriteString("\n## Manual Hotspots\n\n| Directory | Matched docs |\n| --- | ---: |\n")
	if len(e.ManualTopDirs) == 0 {
		b.WriteString("| None | 0 |\n")
		return
	}
	for _, dir := range e.ManualTopDirs {
		fmt.Fprintf(b, "| `%s` | %d |\n", dir.Path, dir.Count)
	}
}

func renderManualSamples(b *strings.Builder, e evidence) {
	b.WriteString("\n## Manual Samples\n\n| Group | Path |\n| --- | --- |\n")
	if len(e.ManualSamples) == 0 {
		b.WriteString("| None | - |\n")
		return
	}
	for _, sample := range e.ManualSamples {
		fmt.Fprintf(b, "| `%s` | `%s` |\n", sample.Group, sample.Path)
	}
}
