package main

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const generatedMarker = "<!-- Generated by "

func scanDocs(root string, m manifest) ([]docClass, []string) {
	manualByPath := manualPathIndex(m)
	var docs []docClass
	var problems []string
	for _, scanRoot := range m.ScanRoots {
		found, err := scanRootDocs(root, scanRoot, m, manualByPath)
		if err != nil {
			problems = append(problems, err.Error())
			continue
		}
		docs = append(docs, found...)
	}
	for _, path := range m.ScanFiles {
		docs = append(docs, scanFileDoc(root, path, m, manualByPath))
	}
	docs = dedupeDocs(docs)
	slices.SortFunc(docs, func(a, b docClass) int { return strings.Compare(a.Path, b.Path) })
	problems = append(problems, validateGeneratedDocs(root, docs)...)
	problems = append(problems, validateGeneratedArtifactBindings(root, docs)...)
	problems = append(problems, validateManualEntries(root, m, docs)...)
	problems = append(problems, validateDirectLoops(docs)...)
	problems = append(problems, validateDirectEvidence(root, docs)...)
	problems = append(problems, validateStandaloneManifests(root, m)...)
	problems = append(problems, validateSourceManifests(root, m)...)
	return docs, problems
}

func scanFileDoc(root, path string, m manifest, manualByPath map[string]manualGroup) docClass {
	return classifyDoc(root, filepath.ToSlash(path), m, manualByPath)
}

func scanRootDocs(root, scanRoot string, m manifest, manualByPath map[string]manualGroup) ([]docClass, error) {
	var docs []docClass
	err := filepath.WalkDir(resolvePath(root, scanRoot), func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(path, ".md") {
			return err
		}
		rel := slashPath(root, path)
		docs = append(docs, classifyDoc(root, rel, m, manualByPath))
		return nil
	})
	return docs, err
}

func classifyDoc(root, rel string, m manifest, manualByPath map[string]manualGroup) docClass {
	text, err := os.ReadFile(resolvePath(root, rel))
	if err == nil && strings.Contains(string(text), generatedMarker) {
		return docClass{Path: rel, Kind: "generated", GeneratorTool: generatedToolFromMarker(string(text))}
	}
	manifestPath := siblingManifest(rel)
	if _, err := os.Stat(resolvePath(root, manifestPath)); err == nil {
		meta := directManifestMetadata(resolvePath(root, manifestPath))
		return docClass{Path: rel, Kind: "direct_ssot", HasLoop: completeLoop(meta.Loop), EvidenceTool: meta.EvidenceTool}
	}
	if group, ok := manualByPath[rel]; ok {
		return docClass{Path: rel, Kind: "manual_registered", Group: group.ID, Reason: group.Reason}
	}
	if group, ok := manualPrefixMatch(m, rel); ok {
		return docClass{Path: rel, Kind: "manual_registered", Group: group.ID, Reason: group.Reason}
	}
	return docClass{Path: rel, Kind: "unregistered_manual"}
}
