package main

const defaultManifest = "docs/30-architecture/config-reference.riido.json"

const evidenceSchema = "riido-control-plane-config-reference-evidence.v1"

const generatedNotice = "<!-- Generated by go run ./tools/configreference -write-doc. Do not edit by hand. -->"
