package main

const (
	defaultManifest = "docs/20-domain/saas-control-plane.riido.json"
	manifestSchema  = "riido-saas-control-plane.v1"
	evidenceSchema  = "riido-saas-control-plane-evidence.v1"
	expectedID      = "saas-control-plane"
)

const generatedNotice = "<!-- Generated by go run ./tools/saascontrolplane -write-doc. Do not edit by hand. -->"

var requiredSharedContracts = []string{
	"github.com/teamswyg/riido-contracts/assignment",
	"github.com/teamswyg/riido-contracts/progressmessage",
	"github.com/teamswyg/riido-contracts/provider/capability",
}
