package main

const (
	defaultManifest = "docs/30-architecture/api-client-delivery.riido.json"
	generatedNotice = "<!-- Generated by tools/apiclientdelivery; edit api-client-delivery.riido.json instead. -->"
	manifestSchema  = "riido-control-plane-api-client-delivery.v1"
)
