package main

import "strings"

const (
	projectionSchema = "riido-control-plane-figma-ai-agent-projection.v1"
	sourceSchema     = "riido-figma-ai-agent-coverage.v1"
	evidenceSchema   = "riido-control-plane-figma-projection-evidence.v1"
	projectionID     = "figma-ai-agent-control-plane-generated-client-projection"
	sourceID         = "figma-v1-22-ai-agent-ui-coverage"
	requiredTask     = "RIID-4810"
	evidenceTool     = "tools/figmaprojection"
	workflow         = ".github/workflows/api-client-delivery.yml"
	evidenceArtifact = "api-client-delivery-evidence"
)

const (
	defaultProjection = "docs/30-architecture/figma-ai-agent-control-plane-projection.riido.json"
	defaultSource     = "contracts/ai-agent-client/figma-ai-agent-coverage.riido.json"
	defaultDoc        = "docs/30-architecture/figma-ai-agent-control-plane-projection.md"
)

const generatedNotice = "<!-- Generated by go run ./tools/figmaprojection -write-doc. Do not edit by hand. -->"

type evidenceLoop struct {
	Observation   string `json:"observation"`
	Hypothesis    string `json:"hypothesis"`
	Execute       string `json:"execute"`
	Evaluate      string `json:"evaluate"`
	Retrospective string `json:"retrospective"`
}

func writeDocFile(root, doc string) error {
	return writeText(repoPath(root, defaultDoc), doc)
}

func completeLoop(loop evidenceLoop) bool {
	for _, value := range []string{
		loop.Observation, loop.Hypothesis, loop.Execute,
		loop.Evaluate, loop.Retrospective,
	} {
		if strings.TrimSpace(value) == "" {
			return false
		}
	}
	return true
}
