package main

const (
	defaultManifest = "docs/30-architecture/store-snapshot-file-outbox.riido.json"
	evidenceSchema  = "riido-store-snapshot-file-outbox-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/storesnapshotoutbox -write-doc. Do not edit by hand. -->"
)
