package main

import (
	"flag"
	"os"
)

const (
	defaultManifest = "docs/30-architecture/store-snapshot-file-outbox.riido.json"
	evidenceSchema  = "riido-store-snapshot-file-outbox-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/storesnapshotoutbox -write-doc. Do not edit by hand. -->"
)

type options struct {
	Repo        string
	Manifest    string
	EvidenceOut string
	WriteDoc    bool
	CheckDoc    bool
}

func main() {
	mustRun(os.Args[1:])
}

func mainRun(args []string) error {
	fs := flag.NewFlagSet("storesnapshotoutbox", flag.ContinueOnError)
	repo := fs.String("repo", ".", "repository root")
	manifestPath := fs.String("manifest", defaultManifest, "snapshot/outbox manifest")
	evidenceOut := fs.String("evidence-out", "", "optional evidence JSON output path")
	writeDoc := fs.Bool("write-doc", false, "write generated reader doc")
	checkDoc := fs.Bool("check-doc", false, "verify generated reader doc")
	if err := fs.Parse(args); err != nil {
		return err
	}
	return run(options{
		Repo: *repo, Manifest: *manifestPath, EvidenceOut: *evidenceOut,
		WriteDoc: *writeDoc, CheckDoc: *checkDoc,
	})
}
