package controlplanegraphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/teamswyg/riido-control-plane/internal/controlplanegraphql/generated"
	"github.com/teamswyg/riido-control-plane/internal/controlplanegraphql/model"
)

// FireError is the resolver for the fireError field.
func (r *queryResolver) FireError(ctx context.Context) (*model.FireErrorVoid, error) {
	return nil, fmt.Errorf("control-plane fireError always fails by contract")
}

// HealthCheck is the resolver for the healthCheck field.
func (r *queryResolver) HealthCheck(ctx context.Context) (int, error) {
	if r.Health == nil {
		return 0, fmt.Errorf("control-plane health use case is not configured")
	}
	status, err := r.Health.HealthCheck(ctx)
	if err != nil {
		return 0, err
	}
	if status != 200 {
		return 0, fmt.Errorf("control-plane health use case returned an invalid status")
	}
	return status, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
