package main

const (
	defaultManifest = "docs/30-architecture/web-frontend-api.riido.json"
	evidenceSchema  = "riido-web-frontend-api-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/webfrontendapi -write-doc. Do not edit by hand. -->"
)
