package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest) string {
	var b strings.Builder
	b.WriteString("# " + m.Title + "\n\n")
	b.WriteString("<!-- Generated by go run ./tools/assignmentjournal -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "> Riido task: %s\n\n", m.RiidoTask)
	b.WriteString("Executable SSOT: [`assignment-operation-journal.riido.json`](assignment-operation-journal.riido.json).\n\n")
	b.WriteString("## Ownership\n\n")
	fmt.Fprintf(&b, "`%s` owns the journal port, claim port, lease/projection shapes, and replay reducer contract.\n\n", m.OwnerPackage)
	renderLoop(&b, m.Loop)
	renderSurfaces(&b, "Ports", m.Ports)
	renderSurfaces(&b, "Records", m.Records)
	renderRules(&b, "Replay Rules", m.ReplayRules)
	renderConstants(&b, m.VersionConstants)
	renderSection(&b, "Non-Goals", m.NonGoals)
	return b.String()
}

func renderSurfaces(b *strings.Builder, title string, surfaces []surface) {
	b.WriteString("## " + title + "\n\n| Name | Role |\n| --- | --- |\n")
	for _, item := range surfaces {
		fmt.Fprintf(b, "| `%s` | %s |\n", item.Name, item.Role)
	}
	b.WriteString("\n")
}

func renderRules(b *strings.Builder, title string, rules []rule) {
	b.WriteString("## " + title + "\n\n| Rule | Kind | Statement |\n| --- | --- | --- |\n")
	for _, rule := range rules {
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", rule.ID, emptyDash(rule.Kind), rule.Rule)
	}
}

func renderConstants(b *strings.Builder, constants []constant) {
	b.WriteString("\n## Version Constants\n\n| Name | Value |\n| --- | --- |\n")
	for _, item := range constants {
		fmt.Fprintf(b, "| `%s` | `%s` |\n", item.Name, item.Value)
	}
}
